### ISSUE TITLE
parser fails to find info section

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-json#108]
The command
```
node app.js -f ../modelica-buildings/Buildings/Controls/OBC/CDL/Continuous/MatrixMax.mo -o json -m cdl -d out
```
returns
```
warn:    Buildings.Controls.OBC.CDL.Continuous.MatrixMax has no info section.
Json file is valid
```
but there is an info section in `MatrixMax.mo` (tested with master branch).

**Comment by JayHuLBL** [comment]
@mwetter Parsing following classes will issue no-info warning:
- `Buildings.Controls.OBC.CDL.Utilities.SunRiseSet`
- `Buildings.Controls.OBC.CDL.Continuous.MatrixMax` 
- `Buildings.Controls.OBC.CDL.Continuous.MatrixMin`

It is because the equation section is not properly closed with `;`. Modelica-json should issue warning in this case.
