### ISSUE TITLE
Hyperlinks reference the wrong version of the library

### ISSUE THREAD

**Issue by mwetter** [lbl-srg/modelica-json#150]
Hyperlinks to the CDL blocks point to, for example,
http://simulationresearch.lbl.gov/modelica/releases/v5.0.1/help/Buildings_Controls_OBC_CDL_Continuous.html#Buildings.Controls.OBC.CDL.Continuous.PID

It should point to the actual version, or to `latest` for the development version e.g., if `v8.0.0` is not a valid link, then link to `latest`.

**Comment by JayHuLBL** [comment]
@mwetter 
To link to the actual version, the parsing process should firstly know where to find the actual version number, which can only be found from the `Buildings.package.mo`. It means that the process should also parse the `Buildings.package.mo` file then obtain the number from the output, or, we add version annotation to the CDL elementary block.

About the alternative link, when say `v8.0.0` is not valid, then link to the `latest`, one potential approach is like [here](https://stackoverflow.com/questions/28919786/alternate-link-in-href-attribute), but I haven't made it work.
```
<a id="button" href="" 
    data-primary-target="http://www1.some-server.example/file"
    data-secondary-target="http://www2.some-server.example/file"
    data-ternary-target="http://www2.some-server.example/file">
    Download
</a>
```
For now, In commit 450eee5, I made the [change](https://github.com/lbl-srg/modelica-json/blob/450eee55034917272d93f28ef1f3bb08229589bb/lib/htmlWriter.js#L566) so that it always link to the latest version.

I agree link to the correct version is important, as our library is evolving so the latest version may not the one used for composing the sequence. For now, it may be good to let it link to the latest one. Let's keep this issue open.

**Comment by mwetter** [comment]
@JayHuLBL Let's leave this issue open so we can add the functionality to look up the version number as specified in the Modelica Language Definition.
